-- ========================================
-- SISTEMA DE PEDIDOS - LANCHONETE
-- PostgreSQL
-- Autora: Beatriz Teodoro
-- ========================================


-- ========================
-- TABELAS
-- ========================

-- Clientes
CREATE TABLE "tbl_clientes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "telefone" varchar(20),
  "endereco" varchar(200),
  "criado_em" timestamp NOT NULL DEFAULT now()
);

-- Categorias
CREATE TABLE "tbl_categorias" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) UNIQUE NOT NULL
);

-- Produtos
CREATE TABLE "tbl_produtos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoria_id" int NOT NULL,
  "nome" varchar(100) NOT NULL,
  "descricao" text,
  "preco" numeric(10,2) NOT NULL CHECK (preco >= 0),
  "disponivel" boolean NOT NULL DEFAULT true
);

-- Funcionários
CREATE TABLE "tbl_funcionarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(255) NOT NULL,
  "cargo" varchar(55),
  "ativo" boolean NOT NULL DEFAULT true
);

-- Pedidos
CREATE TABLE "tbl_pedidos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int NOT NULL,
  "funcionario_id" int NOT NULL,
  "tipo_pedido" varchar(30) NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'PENDENTE',
  "observacao" text,
  "total" numeric(10,2) DEFAULT 0,
  "criado_em" timestamp NOT NULL DEFAULT now(),
  "atualizado_em" timestamp NOT NULL DEFAULT now(),
  CHECK (status IN ('PENDENTE','EM_PREPARO','PRONTO','ENTREGUE','CANCELADO'))
);

-- Itens do pedido
CREATE TABLE "tbl_itens_pedido" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" int NOT NULL,
  "produto_id" int NOT NULL,
  "quantidade" int NOT NULL CHECK (quantidade > 0),
  "preco_unitario" numeric(10,2) NOT NULL,
  "subtotal" numeric(10,2) NOT NULL
);


-- ========================
-- RELACIONAMENTOS (FK)
-- ========================

ALTER TABLE "tbl_produtos"
ADD FOREIGN KEY ("categoria_id") REFERENCES "tbl_categorias" ("id");

ALTER TABLE "tbl_pedidos"
ADD FOREIGN KEY ("cliente_id") REFERENCES "tbl_clientes" ("id");

ALTER TABLE "tbl_pedidos"
ADD FOREIGN KEY ("funcionario_id") REFERENCES "tbl_funcionarios" ("id");

ALTER TABLE "tbl_itens_pedido"
ADD FOREIGN KEY ("pedido_id") REFERENCES "tbl_pedidos" ("id");

ALTER TABLE "tbl_itens_pedido"
ADD FOREIGN KEY ("produto_id") REFERENCES "tbl_produtos" ("id");


-- ========================
-- AUTOMAÇÃO (TRIGGERS)
-- ========================

-- Calcula subtotal automaticamente
CREATE OR REPLACE FUNCTION calcular_subtotal()
RETURNS TRIGGER AS $$
BEGIN
  NEW.subtotal := NEW.quantidade * NEW.preco_unitario;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_subtotal
BEFORE INSERT OR UPDATE ON tbl_itens_pedido
FOR EACH ROW
EXECUTE FUNCTION calcular_subtotal();


-- Atualiza total do pedido automaticamente
CREATE OR REPLACE FUNCTION atualizar_total_pedido()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE tbl_pedidos
  SET total = (
    SELECT COALESCE(SUM(subtotal),0)
    FROM tbl_itens_pedido
    WHERE pedido_id = NEW.pedido_id
  )
  WHERE id = NEW.pedido_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_total_pedido
AFTER INSERT OR UPDATE ON tbl_itens_pedido
FOR EACH ROW
EXECUTE FUNCTION atualizar_total_pedido();


-- ========================
-- DADOS (INSERT)
-- ========================

INSERT INTO tbl_clientes (nome, email)
VALUES ('João Silva', 'joao@email.com');

INSERT INTO tbl_funcionarios (nome)
VALUES ('Atendente 1');

INSERT INTO tbl_categorias (nome)
VALUES ('Lanche');

INSERT INTO tbl_produtos (categoria_id, nome, preco)
VALUES (1, 'Hamburguer', 15.00);

INSERT INTO tbl_pedidos (cliente_id, funcionario_id, tipo_pedido)
VALUES (1, 1, 'BALCAO');

-- Agora NÃO precisa passar subtotal (trigger calcula)
INSERT INTO tbl_itens_pedido (pedido_id, produto_id, quantidade, preco_unitario, subtotal)
VALUES (1, 1, 2, 15.00, 0);


-- ========================
-- CONSULTAS
-- ========================

-- Dados básicos
SELECT * FROM tbl_clientes;
SELECT * FROM tbl_pedidos;
SELECT * FROM tbl_itens_pedido;

-- Pedido com detalhes
SELECT 
  p.id AS pedido,
  c.nome AS cliente,
  pr.nome AS produto,
  ip.quantidade,
  ip.subtotal
FROM tbl_pedidos p
JOIN tbl_clientes c ON p.cliente_id = c.id
JOIN tbl_itens_pedido ip ON ip.pedido_id = p.id
JOIN tbl_produtos pr ON ip.produto_id = pr.id;

-- Faturamento por dia
SELECT 
  DATE(p.criado_em) AS data,
  SUM(ip.subtotal) AS faturamento
FROM tbl_pedidos p
JOIN tbl_itens_pedido ip ON ip.pedido_id = p.id
WHERE p.status <> 'CANCELADO'
GROUP BY DATE(p.criado_em)
ORDER BY data;